namespace FPackerLibrary.P3D.Models; 

public enum LodName {
    ViewGunner,
    ViewPilot,
    ViewCargo,
    Geometry,
    Memory,
    LandContact,
    Roadway,
    Paths,
    HitPoints,
    ViewGeometry,
    FireGeometry,
    ViewCargoGeometry,
    ViewCargoFireGeometry,
    ViewCommander,
    ViewCommanderGeometry,
    ViewCommanderFireGeometry,
    ViewPilotGeometry,
    ViewPilotFireGeometry,
    ViewGunnerGeometry,
    ViewGunnerFireGeometry,
    SubParts,
    ShadowVolumeViewCargo,
    ShadowVolumeViewPilot,
    ShadowVolumeViewGunner,
    Wreck,
    PhysX,
    ShadowVolume,
    Resolution,
    Undefined
}