name: Build main App

on:
  push:
    tags:
      - '*'
env:
    target: 'FPacker 2.0'
    
jobs:
  main:

    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
      with:
        submodules: recursive
            
    - name: Set Version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${{ github.ref }})
            
#    - name: Update Assembly version
#      shell: powershell
#      run: (Get-Content $env:target\Properties\AssemblyInfo.cs).replace('1.0.0.0', '${{ github.ref }}').replace("refs/tags/v", "") | Set-Content $env:target\Properties\AssemblyInfo.cs
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
     
    - name: Restore NuGet Packages
      run: nuget restore $env:target.sln
        
    - name: Build
      run: msbuild $env:target.sln /p:Configuration=Release
              
    - name: Upload dll Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: $env:target.exe
        path: publish\$env:target.exe

    - name: Add to releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          publish\$env:target.exe
